name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker/compose:latest
        env:
          DOCKER_COMPOSE_VERSION: 1.29.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps
        env:
          DOCKER_HOST: tcp://localhost:2375
